### ISSUE TITLE
Update/publish for scala 2.12

### ISSUE THREAD

**Issue by cpnielsen** [pvorb/scala-pandoc#3]
Hi

Any chance you could publish this again for scala 2.12? It seems to be perfectly fitted for an "embedded" pandoc workflow, and it's the only library for Java/scala that works without working with files.

Thank you!

**Comment by pvorb** [comment]
Oh, I'm sorry. I totally forgot there was an issue in here. 😣

If you still need it, I can rebuild this for Scala x.y. I wasn't aware that anyone would find this library useful.
